[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
version = "1.0.0"
description = "Reusable maze generation library with a hex wall encoding."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
keywords = ["maze", "generator", "algorithm", "graph"]

authors = [
    { name = "Khalid and Ivan" }
]

dependencies = []

# Optional CLI entry point (you can remove if not needed)
[project.scripts]
mazegen = "utils.parse_arges:main"


[tool.setuptools.packages.find]
where = ["."]
include = ["mazegen*", "utils*"]

# Type checking
[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_ignores = true
disallow_untyped_defs = true
check_untyped_defs = true

# Linting
[tool.flake8]
max-line-length = 99
exclude = [".git", "__pycache__", "*.egg-info", "dist", "build"]